import Head from "next/head";
import Image from "next/image";
import dynamic from "next/dynamic";
import styles from "../styles/Home.module.css";

import Header from "@components/Header";
import Footer from "@components/Footer";

var x = true;
// debugger;

export default function Home() {
  return (
    <div className={styles.container}>
      {/* <div className='container'> */}
      <Head>
        <title>MOZG | Next</title>
        <meta name='description' content='Generated by create next app' />
        <link
          href='https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css'
          rel='stylesheet'
          integrity='sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC'
          crossOrigin='anonymous'
        ></link>
        <script
          src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js'
          crossOrigin='anonymous'
        ></script>
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout />
    </div>
  );
}

const Layout_Header = () => {
  return (
    <header>
      <nav className='navbar navbar-expand-md navbar-dark mb-1'>
        <div className='container'>
          <div className='text-center'>
            <a className=' ' href={process.env.PUBLIC_URL}>
              <img
                src='/images/logos/Russian_Army_Star.svg'
                width='50'
                height='50'
                className='d-inline-block align-top logo animated infinite bounce delay-2s'
                alt=''
              />
            </a>
            <p>
              <span className='badge bg-dark'>MOZG</span>
            </p>
          </div>
          <button
            className='navbar-toggler'
            type='button'
            data-bs-toggle='collapse'
            data-bs-target='#navbarSupportedContent'
            aria-controls='navbarSupportedContent'
            aria-expanded='false'
            aria-label='Toggle navigation'
          >
            <span className='navbar-toggler-icon'></span>
          </button>
          <div className='collapse navbar-collapse' id='navbarSupportedContent'>
            <ul className='navbar-nav me-auto mb-2 mb-lg-0'>
              <li className=''>
                <a
                  href='/'
                  target='_blank'
                  className='nav-link active'
                  rel='noopener noreferrer'
                >
                  Visão geral
                </a>
              </li>
              <li className='nav-item '>
                <a
                  href='https://mozg.com.br/curriculum/'
                  target='_blank'
                  className='nav-link '
                  rel='noopener noreferrer'
                >
                  Curriculum
                </a>
              </li>
              <li className='nav-item  '>
                <a
                  href='https://mozg.com.br/curriculum/'
                  target='_blank'
                  className='nav-link '
                  rel='noopener noreferrer'
                >
                  Chart.js
                </a>
              </li>
              <li className='nav-item'>
                <a
                  className='nav-link disabled'
                  href='#'
                  tabIndex='-1'
                  aria-disabled='true'
                >
                  Em breve
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
  );
};

const Layout_Footer = () => (
  <>
    <footer className='bg-dark '>
      <div className='footer'>
        <div className='container'>
          <div className='row'>
            <div className='col-lg-2 col-md-2 col-sm-4 col-xs-6'>
              <h3> Páginas </h3>
              <ul>
                <li>
                  <a className='footer-link' href='/'>
                    <i className=' icon'></i>Visão geral
                  </a>
                </li>
                <li>
                  <a
                    className='footer-link'
                    href='https://mozg.com.br/curriculum/'
                  >
                    <i className=' icon'></i>Curriculum
                  </a>
                </li>
              </ul>
            </div>
            <div className='col-lg-2 col-md-2 col-sm-4 col-xs-6'>
              <h3> Social </h3>
              <ul>
                <li>
                  <a
                    className='footer-link'
                    href='https://twitter.com/{{ site.twitter.username }}'
                  >
                    <i className='icon twitter'></i>Twitter
                  </a>
                </li>
                <li>
                  <a
                    className='footer-link'
                    className='item'
                    href='https://www.youtube.com/channel/UCiXR9cKwxNKMehSnqXvhtug/videos'
                  >
                    <i className='icon youtube'></i>YouTube
                  </a>
                </li>
                <li>
                  <a
                    className='footer-link'
                    href='https://www.facebook.com/{{ site.facebook_username }}'
                  >
                    <i className='icon facebook'></i>Facebook
                  </a>
                </li>
                <li>
                  <a
                    className='footer-link'
                    href='https://mozgbrasil.wordpress.com/'
                  >
                    <i className='icon wordpress'></i>WordPress
                  </a>
                </li>
                <li>
                  <a
                    className='footer-link'
                    href='http://mozgbrasil.blogspot.com.br/'
                  >
                    <i className='icon google'></i>Blogger
                  </a>
                </li>
                <li>
                  <a className='footer-link' href='http://mozg.negocio.site'>
                    <i className='icon google'></i>Google My Business
                  </a>
                </li>
                <li>
                  <a
                    className='footer-link'
                    href='https://wakatime.com/@mozgbrasil'
                  >
                    <i className='icon google plus'></i>WakaTime
                  </a>
                </li>
              </ul>
            </div>

            {process.env.REACT_APP_BUILD_TYP === "web-extension" ? (
              ""
            ) : (
              <>
                <div className='col-lg-2 col-md-2 col-sm-4 col-xs-6'>
                  <h3> Widgets </h3>
                </div>
              </>
            )}

            <div className='col-lg-2 col-md-2 col-sm-4 col-xs-6'>
              <h3> Repositórios </h3>
              <ul>
                <li>
                  <a
                    className='footer-link'
                    href='https://github.com/mozgbrasil/'
                  >
                    GitHub
                  </a>
                </li>
                <li>
                  <a
                    className='footer-link'
                    href='https://gitlab.com/mozgbrasil'
                  >
                    Gitlab
                  </a>
                </li>
                <li>
                  <a
                    className='footer-link'
                    href='https://bitbucket.org/mozgbrasil/'
                  >
                    Bitbucket
                  </a>
                </li>
                <li>
                  <a
                    className='footer-link'
                    href='https://packagist.org/packages/mozgbrasil/'
                  >
                    Packagist
                  </a>
                </li>
                <li>
                  <a className='footer-link' href='https://www.npmjs.com/~mozg'>
                    NPM
                  </a>
                </li>
                <li>
                  <a
                    className='footer-link'
                    href='https://launchpad.net/~mozgbrasil'
                  >
                    Launchpad
                  </a>
                </li>
              </ul>
            </div>
            <div className='col-lg-3 col-md-3 col-sm-6 col-xs-12'>
              <h3> Parceiros </h3>
              <ul>
                <li>
                  <a
                    className='footer-link'
                    href='https://www.cerebrum.com.br/'
                  >
                    <i className='icon sitemap'></i>CEREBRUM
                  </a>
                </li>
                <li>
                  <a
                    className='footer-link'
                    href='https://www.comunidademagento.com.br/'
                  >
                    Comunidade Magento
                  </a>
                </li>
                <li>
                  <a className='footer-link' href='https://magento.com/'>
                    Magento
                  </a>
                </li>
                <li>
                  <a
                    className='footer-link'
                    href='http://www.cloudways.com/en/?id=35053'
                  >
                    Cloudways
                  </a>
                </li>
                <li>
                  <a className='footer-link' href='https://reactjs.org/'>
                    <i className='icon sitemap'></i>React
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div className='footer-bottom'>
        <div className='container'>
          <p className='pull-left'>Copyright © 2016-2021 MOZG</p>
        </div>
        {/* <div className="container">&nbsp;</div> */}
      </div>
    </footer>
  </>
);

// const Fullscreen = dynamic(() =>
//   import("codepen.io/add-fullscreen-toggle-to-your-pen")
// );

// const AddToHomescreen = dynamic(() => import("@mozg/common/add-to-homescreen"));

// const GravityAnimatedPoster = dynamic(() =>
//   import("codepen.io/gravity-animated-poster")
// );

const Layout = () => {
  return (
    <>
      <Layout_Header />
      <main>
        <div className='container'>
          <div className='row'>
            <h2>Next.js </h2>
            <p>Referências</p>
            {/* <MainRoutes /> */}
            <p>
              <a href='https://nextjs.org/'>nextjs.org</a>
            </p>
            <p>
              <a href='https://nextjs.org/docs/api-reference/create-next-app'>
                vercel/next.js
              </a>
            </p>
            <hr />
            {/* <Crown /> */}
          </div>

          {/* <div className='row'>
            <div className='col-sm-6'>
              <h2>Heading</h2>
              <p>
                Donec id elit non mi porta gravida at eget metus. Fusce dapibus,
                tellus ac cursus commodo, tortor mauris condimentum nibh, ut
                fermentum massa justo sit amet risus. Etiam porta sem malesuada
                magna mollis euismod. Donec sed odio dui.
              </p>
              <p>
                <a className='btn btn-secondary' href='#' role='button'>
                  View details »
                </a>
              </p>
            </div>
            <div className='col-sm-6'>
              <h2>Heading</h2>
              <p>
                Donec id elit non mi porta gravida at eget metus. Fusce dapibus,
                tellus ac cursus commodo, tortor mauris condimentum nibh, ut
                fermentum massa justo sit amet risus. Etiam porta sem malesuada
                magna mollis euismod. Donec sed odio dui.
              </p>
              <p>
                <a className='btn btn-secondary' href='#' role='button'>
                  View details »
                </a>
              </p>
            </div>
            <div className='col-sm-6'>
              <h2>Heading</h2>
              <p>
                Donec id elit non mi porta gravida at eget metus. Fusce dapibus,
                tellus ac cursus commodo, tortor mauris condimentum nibh, ut
                fermentum massa justo sit amet risus. Etiam porta sem malesuada
                magna mollis euismod. Donec sed odio dui.
              </p>
              <p>
                <a className='btn btn-secondary' href='#' role='button'>
                  View details »
                </a>
              </p>
            </div>
            <div className='col-sm-6'>
              <h2>Heading</h2>
              <p>
                Donec id elit non mi porta gravida at eget metus. Fusce dapibus,
                tellus ac cursus commodo, tortor mauris condimentum nibh, ut
                fermentum massa justo sit amet risus. Etiam porta sem malesuada
                magna mollis euismod. Donec sed odio dui.
              </p>
              <p>
                <a className='btn btn-secondary' href='#' role='button'>
                  View details »
                </a>
              </p>
            </div>
            <div className='col-sm-6'>
              <h2>Heading</h2>
              <p>
                Donec id elit non mi porta gravida at eget metus. Fusce dapibus,
                tellus ac cursus commodo, tortor mauris condimentum nibh, ut
                fermentum massa justo sit amet risus. Etiam porta sem malesuada
                magna mollis euismod. Donec sed odio dui.
              </p>
              <p>
                <a className='btn btn-secondary' href='#' role='button'>
                  View details »
                </a>
              </p>
            </div>
            <div className='col-sm-6'>
              <h2>Heading</h2>
              <p>
                Donec id elit non mi porta gravida at eget metus. Fusce dapibus,
                tellus ac cursus commodo, tortor mauris condimentum nibh, ut
                fermentum massa justo sit amet risus. Etiam porta sem malesuada
                magna mollis euismod. Donec sed odio dui.
              </p>
              <p>
                <a className='btn btn-secondary' href='#' role='button'>
                  View details »
                </a>
              </p>
            </div>
            <div className='col-sm-6'>
              <h2>Heading</h2>
              <p>
                Donec id elit non mi porta gravida at eget metus. Fusce dapibus,
                tellus ac cursus commodo, tortor mauris condimentum nibh, ut
                fermentum massa justo sit amet risus. Etiam porta sem malesuada
                magna mollis euismod. Donec sed odio dui.
              </p>
              <p>
                <a className='btn btn-secondary' href='#' role='button'>
                  View details »
                </a>
              </p>
            </div>
            <div className='col-sm-6'>
              <h2>Heading</h2>
              <p>
                Donec id elit non mi porta gravida at eget metus. Fusce dapibus,
                tellus ac cursus commodo, tortor mauris condimentum nibh, ut
                fermentum massa justo sit amet risus. Etiam porta sem malesuada
                magna mollis euismod. Donec sed odio dui.
              </p>
              <p>
                <a className='btn btn-secondary' href='#' role='button'>
                  View details »
                </a>
              </p>
            </div>
            <div className='col-sm-6'>
              <h2>Heading</h2>
              <p>
                Donec id elit non mi porta gravida at eget metus. Fusce dapibus,
                tellus ac cursus commodo, tortor mauris condimentum nibh, ut
                fermentum massa justo sit amet risus. Etiam porta sem malesuada
                magna mollis euismod. Donec sed odio dui.
              </p>
              <p>
                <a className='btn btn-secondary' href='#' role='button'>
                  View details »
                </a>
              </p>
            </div>
            <div className='col-sm-6'>
              <h2>Heading</h2>
              <p>
                Donec id elit non mi porta gravida at eget metus. Fusce dapibus,
                tellus ac cursus commodo, tortor mauris condimentum nibh, ut
                fermentum massa justo sit amet risus. Etiam porta sem malesuada
                magna mollis euismod. Donec sed odio dui.
              </p>
              <p>
                <a className='btn btn-secondary' href='#' role='button'>
                  View details »
                </a>
              </p>
            </div>
            <div className='col-sm-6'>
              <h2>Heading</h2>
              <p>
                Donec id elit non mi porta gravida at eget metus. Fusce dapibus,
                tellus ac cursus commodo, tortor mauris condimentum nibh, ut
                fermentum massa justo sit amet risus. Etiam porta sem malesuada
                magna mollis euismod. Donec sed odio dui.
              </p>
              <p>
                <a className='btn btn-secondary' href='#' role='button'>
                  View details »
                </a>
              </p>
            </div>
          </div> */}
        </div>
      </main>
      <Layout_Footer />
      {/* <Fullscreen />
      <AddToHomescreen />
      <GravityAnimatedPoster /> */}
    </>
  );
};

const Layout_1 = () => {
  return (
    <>
      <main>
        <Header title='Welcome to my app!' />
        <p className='description'>
          Get started by editing <code>pages/index.js</code>
        </p>
      </main>

      <Footer />
    </>
  );
};
